// Code generated by Slice Machine. DO NOT EDIT.

import Menus from './Menus';
import Textbox from './Textbox';

export {
	Menus,
	Textbox,
};

export const components = {
	menus: Menus,
	textbox: Textbox,
};
