export const GetSNP500 = () => {
  return [
    {
      Symbol: "MMM",
      Name: "3M",
      Sector: "Industrials",
    },
    {
      Symbol: "AOS",
      Name: "A. O. Smith",
      Sector: "Industrials",
    },
    {
      Symbol: "ABT",
      Name: "Abbott Laboratories",
      Sector: "Health Care",
    },
    {
      Symbol: "ABBV",
      Name: "AbbVie",
      Sector: "Health Care",
    },
    {
      Symbol: "ABMD",
      Name: "Abiomed",
      Sector: "Health Care",
    },
    {
      Symbol: "ACN",
      Name: "Accenture",
      Sector: "Information Technology",
    },
    {
      Symbol: "ATVI",
      Name: "Activision Blizzard",
      Sector: "Communication Services",
    },
    {
      Symbol: "ADM",
      Name: "ADM",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "ADBE",
      Name: "Adobe",
      Sector: "Information Technology",
    },
    {
      Symbol: "AAP",
      Name: "Advance Auto Parts",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "AMD",
      Name: "Advanced Micro Devices",
      Sector: "Information Technology",
    },
    {
      Symbol: "AES",
      Name: "AES Corp",
      Sector: "Utilities",
    },
    {
      Symbol: "AFL",
      Name: "Aflac",
      Sector: "Financials",
    },
    {
      Symbol: "A",
      Name: "Agilent Technologies",
      Sector: "Health Care",
    },
    {
      Symbol: "APD",
      Name: "Air Products & Chemicals",
      Sector: "Materials",
    },
    {
      Symbol: "AKAM",
      Name: "Akamai Technologies",
      Sector: "Information Technology",
    },
    {
      Symbol: "ALK",
      Name: "Alaska Air Group",
      Sector: "Industrials",
    },
    {
      Symbol: "ALB",
      Name: "Albemarle Corporation",
      Sector: "Materials",
    },
    {
      Symbol: "ARE",
      Name: "Alexandria Real Estate Equities",
      Sector: "Real Estate",
    },
    {
      Symbol: "ALGN",
      Name: "Align Technology",
      Sector: "Health Care",
    },
    {
      Symbol: "ALLE",
      Name: "Allegion",
      Sector: "Industrials",
    },
    {
      Symbol: "LNT",
      Name: "Alliant Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "ALL",
      Name: "Allstate Corp",
      Sector: "Financials",
    },
    {
      Symbol: "GOOGL",
      Name: "Alphabet (Class A)",
      Sector: "Communication Services",
    },
    {
      Symbol: "GOOG",
      Name: "Alphabet (Class C)",
      Sector: "Communication Services",
    },
    {
      Symbol: "MO",
      Name: "Altria Group",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "AMZN",
      Name: "Amazon",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "AMCR",
      Name: "Amcor",
      Sector: "Materials",
    },
    {
      Symbol: "AEE",
      Name: "Ameren Corp",
      Sector: "Utilities",
    },
    {
      Symbol: "AAL",
      Name: "American Airlines Group",
      Sector: "Industrials",
    },
    {
      Symbol: "AEP",
      Name: "American Electric Power",
      Sector: "Utilities",
    },
    {
      Symbol: "AXP",
      Name: "American Express",
      Sector: "Financials",
    },
    {
      Symbol: "AIG",
      Name: "American International Group",
      Sector: "Financials",
    },
    {
      Symbol: "AMT",
      Name: "American Tower",
      Sector: "Real Estate",
    },
    {
      Symbol: "AWK",
      Name: "American Water Works",
      Sector: "Utilities",
    },
    {
      Symbol: "AMP",
      Name: "Ameriprise Financial",
      Sector: "Financials",
    },
    {
      Symbol: "ABC",
      Name: "AmerisourceBergen",
      Sector: "Health Care",
    },
    {
      Symbol: "AME",
      Name: "Ametek",
      Sector: "Industrials",
    },
    {
      Symbol: "AMGN",
      Name: "Amgen",
      Sector: "Health Care",
    },
    {
      Symbol: "APH",
      Name: "Amphenol",
      Sector: "Information Technology",
    },
    {
      Symbol: "ADI",
      Name: "Analog Devices",
      Sector: "Information Technology",
    },
    {
      Symbol: "ANSS",
      Name: "Ansys",
      Sector: "Information Technology",
    },
    {
      Symbol: "ANTM",
      Name: "Anthem",
      Sector: "Health Care",
    },
    {
      Symbol: "AON",
      Name: "Aon",
      Sector: "Financials",
    },
    {
      Symbol: "APA",
      Name: "APA Corporation",
      Sector: "Energy",
    },
    {
      Symbol: "AAPL",
      Name: "Apple",
      Sector: "Information Technology",
    },
    {
      Symbol: "AMAT",
      Name: "Applied Materials",
      Sector: "Information Technology",
    },
    {
      Symbol: "APTV",
      Name: "Aptiv",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "ANET",
      Name: "Arista Networks",
      Sector: "Information Technology",
    },
    {
      Symbol: "AJG",
      Name: "Arthur J. Gallagher & Co.",
      Sector: "Financials",
    },
    {
      Symbol: "AIZ",
      Name: "Assurant",
      Sector: "Financials",
    },
    {
      Symbol: "T",
      Name: "AT&T",
      Sector: "Communication Services",
    },
    {
      Symbol: "ATO",
      Name: "Atmos Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "ADSK",
      Name: "Autodesk",
      Sector: "Information Technology",
    },
    {
      Symbol: "ADP",
      Name: "Automatic Data Processing",
      Sector: "Information Technology",
    },
    {
      Symbol: "AZO",
      Name: "AutoZone",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "AVB",
      Name: "AvalonBay Communities",
      Sector: "Real Estate",
    },
    {
      Symbol: "AVY",
      Name: "Avery Dennison",
      Sector: "Materials",
    },
    {
      Symbol: "BKR",
      Name: "Baker Hughes",
      Sector: "Energy",
    },
    {
      Symbol: "BLL",
      Name: "Ball Corp",
      Sector: "Materials",
    },
    {
      Symbol: "BAC",
      Name: "Bank of America",
      Sector: "Financials",
    },
    {
      Symbol: "BBWI",
      Name: "Bath & Body Works Inc.",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "BAX",
      Name: "Baxter International",
      Sector: "Health Care",
    },
    {
      Symbol: "BDX",
      Name: "Becton Dickinson",
      Sector: "Health Care",
    },
    {
      Symbol: "BRK.B",
      Name: "Berkshire Hathaway",
      Sector: "Financials",
    },
    {
      Symbol: "BBY",
      Name: "Best Buy",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "BIO",
      Name: "Bio-Rad Laboratories",
      Sector: "Health Care",
    },
    {
      Symbol: "TECH",
      Name: "Bio-Techne",
      Sector: "Health Care",
    },
    {
      Symbol: "BIIB",
      Name: "Biogen",
      Sector: "Health Care",
    },
    {
      Symbol: "BLK",
      Name: "BlackRock",
      Sector: "Financials",
    },
    {
      Symbol: "BK",
      Name: "BNY Mellon",
      Sector: "Financials",
    },
    {
      Symbol: "BA",
      Name: "Boeing",
      Sector: "Industrials",
    },
    {
      Symbol: "BKNG",
      Name: "Booking Holdings",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "BWA",
      Name: "BorgWarner",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "BXP",
      Name: "Boston Properties",
      Sector: "Real Estate",
    },
    {
      Symbol: "BSX",
      Name: "Boston Scientific",
      Sector: "Health Care",
    },
    {
      Symbol: "BMY",
      Name: "Bristol Myers Squibb",
      Sector: "Health Care",
    },
    {
      Symbol: "AVGO",
      Name: "Broadcom",
      Sector: "Information Technology",
    },
    {
      Symbol: "BR",
      Name: "Broadridge Financial Solutions",
      Sector: "Information Technology",
    },
    {
      Symbol: "BRO",
      Name: "Brown & Brown",
      Sector: "Financials",
    },
    {
      Symbol: "BF.B",
      Name: "Brown–Forman",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CHRW",
      Name: "C. H. Robinson",
      Sector: "Industrials",
    },
    {
      Symbol: "CDNS",
      Name: "Cadence Design Systems",
      Sector: "Information Technology",
    },
    {
      Symbol: "CZR",
      Name: "Caesars Entertainment",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "CPB",
      Name: "Campbell Soup",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "COF",
      Name: "Capital One Financial",
      Sector: "Financials",
    },
    {
      Symbol: "CAH",
      Name: "Cardinal Health",
      Sector: "Health Care",
    },
    {
      Symbol: "KMX",
      Name: "CarMax",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "CCL",
      Name: "Carnival Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "CARR",
      Name: "Carrier Global",
      Sector: "Industrials",
    },
    {
      Symbol: "CTLT",
      Name: "Catalent",
      Sector: "Health Care",
    },
    {
      Symbol: "CAT",
      Name: "Caterpillar",
      Sector: "Industrials",
    },
    {
      Symbol: "CBOE",
      Name: "Cboe Global Markets",
      Sector: "Financials",
    },
    {
      Symbol: "CBRE",
      Name: "CBRE",
      Sector: "Real Estate",
    },
    {
      Symbol: "CDW",
      Name: "CDW",
      Sector: "Information Technology",
    },
    {
      Symbol: "CE",
      Name: "Celanese",
      Sector: "Materials",
    },
    {
      Symbol: "CNC",
      Name: "Centene Corporation",
      Sector: "Health Care",
    },
    {
      Symbol: "CNP",
      Name: "CenterPoint Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "CDAY",
      Name: "Ceridian",
      Sector: "Information Technology",
    },
    {
      Symbol: "CERN",
      Name: "Cerner",
      Sector: "Health Care",
    },
    {
      Symbol: "CF",
      Name: "CF Industries",
      Sector: "Materials",
    },
    {
      Symbol: "CRL",
      Name: "Charles River Laboratories",
      Sector: "Health Care",
    },
    {
      Symbol: "SCHW",
      Name: "Charles Schwab Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "CHTR",
      Name: "Charter Communications",
      Sector: "Communication Services",
    },
    {
      Symbol: "CVX",
      Name: "Chevron Corporation",
      Sector: "Energy",
    },
    {
      Symbol: "CMG",
      Name: "Chipotle Mexican Grill",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "CB",
      Name: "Chubb",
      Sector: "Financials",
    },
    {
      Symbol: "CHD",
      Name: "Church & Dwight",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CI",
      Name: "Cigna",
      Sector: "Health Care",
    },
    {
      Symbol: "CINF",
      Name: "Cincinnati Financial",
      Sector: "Financials",
    },
    {
      Symbol: "CTAS",
      Name: "Cintas Corporation",
      Sector: "Industrials",
    },
    {
      Symbol: "CSCO",
      Name: "Cisco Systems",
      Sector: "Information Technology",
    },
    {
      Symbol: "C",
      Name: "Citigroup",
      Sector: "Financials",
    },
    {
      Symbol: "CFG",
      Name: "Citizens Financial Group",
      Sector: "Financials",
    },
    {
      Symbol: "CTXS",
      Name: "Citrix Systems",
      Sector: "Information Technology",
    },
    {
      Symbol: "CLX",
      Name: "Clorox",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CME",
      Name: "CME Group",
      Sector: "Financials",
    },
    {
      Symbol: "CMS",
      Name: "CMS Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "KO",
      Name: "Coca-Cola Company",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CTSH",
      Name: "Cognizant Technology Solutions",
      Sector: "Information Technology",
    },
    {
      Symbol: "CL",
      Name: "Colgate-Palmolive",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CMCSA",
      Name: "Comcast",
      Sector: "Communication Services",
    },
    {
      Symbol: "CMA",
      Name: "Comerica",
      Sector: "Financials",
    },
    {
      Symbol: "CAG",
      Name: "Conagra Brands",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "COP",
      Name: "ConocoPhillips",
      Sector: "Energy",
    },
    {
      Symbol: "ED",
      Name: "Consolidated Edison",
      Sector: "Utilities",
    },
    {
      Symbol: "STZ",
      Name: "Constellation Brands",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CPRT",
      Name: "Copart",
      Sector: "Industrials",
    },
    {
      Symbol: "GLW",
      Name: "Corning",
      Sector: "Information Technology",
    },
    {
      Symbol: "CTVA",
      Name: "Corteva",
      Sector: "Materials",
    },
    {
      Symbol: "COST",
      Name: "Costco",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "CTRA",
      Name: "Coterra",
      Sector: "Energy",
    },
    {
      Symbol: "CCI",
      Name: "Crown Castle",
      Sector: "Real Estate",
    },
    {
      Symbol: "CSX",
      Name: "CSX",
      Sector: "Industrials",
    },
    {
      Symbol: "CMI",
      Name: "Cummins",
      Sector: "Industrials",
    },
    {
      Symbol: "CVS",
      Name: "CVS Health",
      Sector: "Health Care",
    },
    {
      Symbol: "DHI",
      Name: "D. R. Horton",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "DHR",
      Name: "Danaher Corporation",
      Sector: "Health Care",
    },
    {
      Symbol: "DRI",
      Name: "Darden Restaurants",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "DVA",
      Name: "DaVita",
      Sector: "Health Care",
    },
    {
      Symbol: "DE",
      Name: "Deere & Co.",
      Sector: "Industrials",
    },
    {
      Symbol: "DAL",
      Name: "Delta Air Lines",
      Sector: "Industrials",
    },
    {
      Symbol: "XRAY",
      Name: "Dentsply Sirona",
      Sector: "Health Care",
    },
    {
      Symbol: "DVN",
      Name: "Devon Energy",
      Sector: "Energy",
    },
    {
      Symbol: "DXCM",
      Name: "DexCom",
      Sector: "Health Care",
    },
    {
      Symbol: "FANG",
      Name: "Diamondback Energy",
      Sector: "Energy",
    },
    {
      Symbol: "DLR",
      Name: "Digital Realty Trust",
      Sector: "Real Estate",
    },
    {
      Symbol: "DFS",
      Name: "Discover Financial Services",
      Sector: "Financials",
    },
    {
      Symbol: "DISCA",
      Name: "Discovery (Series A)",
      Sector: "Communication Services",
    },
    {
      Symbol: "DISCK",
      Name: "Discovery (Series C)",
      Sector: "Communication Services",
    },
    {
      Symbol: "DISH",
      Name: "Dish Network",
      Sector: "Communication Services",
    },
    {
      Symbol: "DG",
      Name: "Dollar General",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "DLTR",
      Name: "Dollar Tree",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "D",
      Name: "Dominion Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "DPZ",
      Name: "Domino's Pizza",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "DOV",
      Name: "Dover Corporation",
      Sector: "Industrials",
    },
    {
      Symbol: "DOW",
      Name: "Dow",
      Sector: "Materials",
    },
    {
      Symbol: "DTE",
      Name: "DTE Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "DUK",
      Name: "Duke Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "DRE",
      Name: "Duke Realty Corp",
      Sector: "Real Estate",
    },
    {
      Symbol: "DD",
      Name: "DuPont",
      Sector: "Materials",
    },
    {
      Symbol: "DXC",
      Name: "DXC Technology",
      Sector: "Information Technology",
    },
    {
      Symbol: "EMN",
      Name: "Eastman Chemical",
      Sector: "Materials",
    },
    {
      Symbol: "ETN",
      Name: "Eaton Corporation",
      Sector: "Industrials",
    },
    {
      Symbol: "EBAY",
      Name: "eBay",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "ECL",
      Name: "Ecolab",
      Sector: "Materials",
    },
    {
      Symbol: "EIX",
      Name: "Edison International",
      Sector: "Utilities",
    },
    {
      Symbol: "EW",
      Name: "Edwards Lifesciences",
      Sector: "Health Care",
    },
    {
      Symbol: "EA",
      Name: "Electronic Arts",
      Sector: "Communication Services",
    },
    {
      Symbol: "LLY",
      Name: "Eli Lilly & Co",
      Sector: "Health Care",
    },
    {
      Symbol: "EMR",
      Name: "Emerson Electric Company",
      Sector: "Industrials",
    },
    {
      Symbol: "ENPH",
      Name: "Enphase Energy",
      Sector: "Information Technology",
    },
    {
      Symbol: "ETR",
      Name: "Entergy",
      Sector: "Utilities",
    },
    {
      Symbol: "EOG",
      Name: "EOG Resources",
      Sector: "Energy",
    },
    {
      Symbol: "EFX",
      Name: "Equifax",
      Sector: "Industrials",
    },
    {
      Symbol: "EQIX",
      Name: "Equinix",
      Sector: "Real Estate",
    },
    {
      Symbol: "EQR",
      Name: "Equity Residential",
      Sector: "Real Estate",
    },
    {
      Symbol: "ESS",
      Name: "Essex Property Trust",
      Sector: "Real Estate",
    },
    {
      Symbol: "EL",
      Name: "Estée Lauder Companies",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "ETSY",
      Name: "Etsy",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "RE",
      Name: "Everest Re",
      Sector: "Financials",
    },
    {
      Symbol: "EVRG",
      Name: "Evergy",
      Sector: "Utilities",
    },
    {
      Symbol: "ES",
      Name: "Eversource Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "EXC",
      Name: "Exelon",
      Sector: "Utilities",
    },
    {
      Symbol: "EXPE",
      Name: "Expedia Group",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "EXPD",
      Name: "Expeditors",
      Sector: "Industrials",
    },
    {
      Symbol: "EXR",
      Name: "Extra Space Storage",
      Sector: "Real Estate",
    },
    {
      Symbol: "XOM",
      Name: "ExxonMobil",
      Sector: "Energy",
    },
    {
      Symbol: "FFIV",
      Name: "F5 Networks",
      Sector: "Information Technology",
    },
    {
      Symbol: "FB",
      Name: "Facebook",
      Sector: "Communication Services",
    },
    {
      Symbol: "FAST",
      Name: "Fastenal",
      Sector: "Industrials",
    },
    {
      Symbol: "FRT",
      Name: "Federal Realty Investment Trust",
      Sector: "Real Estate",
    },
    {
      Symbol: "FDX",
      Name: "FedEx",
      Sector: "Industrials",
    },
    {
      Symbol: "FIS",
      Name: "Fidelity National Information Services",
      Sector: "Information Technology",
    },
    {
      Symbol: "FITB",
      Name: "Fifth Third Bancorp",
      Sector: "Financials",
    },
    {
      Symbol: "FRC",
      Name: "First Republic Bank",
      Sector: "Financials",
    },
    {
      Symbol: "FE",
      Name: "FirstEnergy",
      Sector: "Utilities",
    },
    {
      Symbol: "FISV",
      Name: "Fiserv",
      Sector: "Information Technology",
    },
    {
      Symbol: "FLT",
      Name: "Fleetcor",
      Sector: "Information Technology",
    },
    {
      Symbol: "FMC",
      Name: "FMC Corporation",
      Sector: "Materials",
    },
    {
      Symbol: "F",
      Name: "Ford",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "FTNT",
      Name: "Fortinet",
      Sector: "Information Technology",
    },
    {
      Symbol: "FTV",
      Name: "Fortive",
      Sector: "Industrials",
    },
    {
      Symbol: "FBHS",
      Name: "Fortune Brands Home & Security",
      Sector: "Industrials",
    },
    {
      Symbol: "FOXA",
      Name: "Fox Corporation (Class A)",
      Sector: "Communication Services",
    },
    {
      Symbol: "FOX",
      Name: "Fox Corporation (Class B)",
      Sector: "Communication Services",
    },
    {
      Symbol: "BEN",
      Name: "Franklin Resources",
      Sector: "Financials",
    },
    {
      Symbol: "FCX",
      Name: "Freeport-McMoRan",
      Sector: "Materials",
    },
    {
      Symbol: "GPS",
      Name: "Gap",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "GRMN",
      Name: "Garmin",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "IT",
      Name: "Gartner",
      Sector: "Information Technology",
    },
    {
      Symbol: "GNRC",
      Name: "Generac Holdings",
      Sector: "Industrials",
    },
    {
      Symbol: "GD",
      Name: "General Dynamics",
      Sector: "Industrials",
    },
    {
      Symbol: "GE",
      Name: "General Electric",
      Sector: "Industrials",
    },
    {
      Symbol: "GIS",
      Name: "General Mills",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "GM",
      Name: "General Motors",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "GPC",
      Name: "Genuine Parts",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "GILD",
      Name: "Gilead Sciences",
      Sector: "Health Care",
    },
    {
      Symbol: "GPN",
      Name: "Global Payments",
      Sector: "Information Technology",
    },
    {
      Symbol: "GL",
      Name: "Globe Life",
      Sector: "Financials",
    },
    {
      Symbol: "GS",
      Name: "Goldman Sachs",
      Sector: "Financials",
    },
    {
      Symbol: "HAL",
      Name: "Halliburton",
      Sector: "Energy",
    },
    {
      Symbol: "HBI",
      Name: "Hanesbrands",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "HAS",
      Name: "Hasbro",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "HCA",
      Name: "HCA Healthcare",
      Sector: "Health Care",
    },
    {
      Symbol: "PEAK",
      Name: "Healthpeak Properties",
      Sector: "Real Estate",
    },
    {
      Symbol: "HSIC",
      Name: "Henry Schein",
      Sector: "Health Care",
    },
    {
      Symbol: "HES",
      Name: "Hess Corporation",
      Sector: "Energy",
    },
    {
      Symbol: "HPE",
      Name: "Hewlett Packard Enterprise",
      Sector: "Information Technology",
    },
    {
      Symbol: "HLT",
      Name: "Hilton Worldwide",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "HOLX",
      Name: "Hologic",
      Sector: "Health Care",
    },
    {
      Symbol: "HD",
      Name: "Home Depot",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "HON",
      Name: "Honeywell",
      Sector: "Industrials",
    },
    {
      Symbol: "HRL",
      Name: "Hormel",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "HST",
      Name: "Host Hotels & Resorts",
      Sector: "Real Estate",
    },
    {
      Symbol: "HWM",
      Name: "Howmet Aerospace",
      Sector: "Industrials",
    },
    {
      Symbol: "HPQ",
      Name: "HP",
      Sector: "Information Technology",
    },
    {
      Symbol: "HUM",
      Name: "Humana",
      Sector: "Health Care",
    },
    {
      Symbol: "HBAN",
      Name: "Huntington Bancshares",
      Sector: "Financials",
    },
    {
      Symbol: "HII",
      Name: "Huntington Ingalls Industries",
      Sector: "Industrials",
    },
    {
      Symbol: "IBM",
      Name: "IBM",
      Sector: "Information Technology",
    },
    {
      Symbol: "IEX",
      Name: "IDEX Corporation",
      Sector: "Industrials",
    },
    {
      Symbol: "IDXX",
      Name: "Idexx Laboratories",
      Sector: "Health Care",
    },
    {
      Symbol: "INFO",
      Name: "IHS Markit",
      Sector: "Industrials",
    },
    {
      Symbol: "ITW",
      Name: "Illinois Tool Works",
      Sector: "Industrials",
    },
    {
      Symbol: "ILMN",
      Name: "Illumina",
      Sector: "Health Care",
    },
    {
      Symbol: "INCY",
      Name: "Incyte",
      Sector: "Health Care",
    },
    {
      Symbol: "IR",
      Name: "Ingersoll Rand",
      Sector: "Industrials",
    },
    {
      Symbol: "INTC",
      Name: "Intel",
      Sector: "Information Technology",
    },
    {
      Symbol: "ICE",
      Name: "Intercontinental Exchange",
      Sector: "Financials",
    },
    {
      Symbol: "IFF",
      Name: "International Flavors & Fragrances",
      Sector: "Materials",
    },
    {
      Symbol: "IP",
      Name: "International Paper",
      Sector: "Materials",
    },
    {
      Symbol: "IPG",
      Name: "Interpublic Group",
      Sector: "Communication Services",
    },
    {
      Symbol: "INTU",
      Name: "Intuit",
      Sector: "Information Technology",
    },
    {
      Symbol: "ISRG",
      Name: "Intuitive Surgical",
      Sector: "Health Care",
    },
    {
      Symbol: "IVZ",
      Name: "Invesco",
      Sector: "Financials",
    },
    {
      Symbol: "IPGP",
      Name: "IPG Photonics",
      Sector: "Information Technology",
    },
    {
      Symbol: "IQV",
      Name: "IQVIA",
      Sector: "Health Care",
    },
    {
      Symbol: "IRM",
      Name: "Iron Mountain",
      Sector: "Real Estate",
    },
    {
      Symbol: "JBHT",
      Name: "J. B. Hunt",
      Sector: "Industrials",
    },
    {
      Symbol: "JKHY",
      Name: "Jack Henry & Associates",
      Sector: "Information Technology",
    },
    {
      Symbol: "J",
      Name: "Jacobs Engineering Group",
      Sector: "Industrials",
    },
    {
      Symbol: "SJM",
      Name: "JM Smucker",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "JNJ",
      Name: "Johnson & Johnson",
      Sector: "Health Care",
    },
    {
      Symbol: "JCI",
      Name: "Johnson Controls",
      Sector: "Industrials",
    },
    {
      Symbol: "JPM",
      Name: "JPMorgan Chase",
      Sector: "Financials",
    },
    {
      Symbol: "JNPR",
      Name: "Juniper Networks",
      Sector: "Information Technology",
    },
    {
      Symbol: "KSU",
      Name: "Kansas City Southern",
      Sector: "Industrials",
    },
    {
      Symbol: "K",
      Name: "Kellogg's",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "KEY",
      Name: "KeyCorp",
      Sector: "Financials",
    },
    {
      Symbol: "KEYS",
      Name: "Keysight Technologies",
      Sector: "Information Technology",
    },
    {
      Symbol: "KMB",
      Name: "Kimberly-Clark",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "KIM",
      Name: "Kimco Realty",
      Sector: "Real Estate",
    },
    {
      Symbol: "KMI",
      Name: "Kinder Morgan",
      Sector: "Energy",
    },
    {
      Symbol: "KLAC",
      Name: "KLA Corporation",
      Sector: "Information Technology",
    },
    {
      Symbol: "KHC",
      Name: "Kraft Heinz",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "KR",
      Name: "Kroger",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "LHX",
      Name: "L3Harris Technologies",
      Sector: "Industrials",
    },
    {
      Symbol: "LH",
      Name: "LabCorp",
      Sector: "Health Care",
    },
    {
      Symbol: "LRCX",
      Name: "Lam Research",
      Sector: "Information Technology",
    },
    {
      Symbol: "LW",
      Name: "Lamb Weston",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "LVS",
      Name: "Las Vegas Sands",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "LEG",
      Name: "Leggett & Platt",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "LDOS",
      Name: "Leidos",
      Sector: "Industrials",
    },
    {
      Symbol: "LEN",
      Name: "Lennar",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "LNC",
      Name: "Lincoln National",
      Sector: "Financials",
    },
    {
      Symbol: "LIN",
      Name: "Linde",
      Sector: "Materials",
    },
    {
      Symbol: "LYV",
      Name: "Live Nation Entertainment",
      Sector: "Communication Services",
    },
    {
      Symbol: "LKQ",
      Name: "LKQ Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "LMT",
      Name: "Lockheed Martin",
      Sector: "Industrials",
    },
    {
      Symbol: "L",
      Name: "Loews Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "LOW",
      Name: "Lowe's",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "LUMN",
      Name: "Lumen Technologies",
      Sector: "Communication Services",
    },
    {
      Symbol: "LYB",
      Name: "LyondellBasell",
      Sector: "Materials",
    },
    {
      Symbol: "MTB",
      Name: "M&T Bank",
      Sector: "Financials",
    },
    {
      Symbol: "MRO",
      Name: "Marathon Oil",
      Sector: "Energy",
    },
    {
      Symbol: "MPC",
      Name: "Marathon Petroleum",
      Sector: "Energy",
    },
    {
      Symbol: "MKTX",
      Name: "MarketAxess",
      Sector: "Financials",
    },
    {
      Symbol: "MAR",
      Name: "Marriott International",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "MMC",
      Name: "Marsh & McLennan",
      Sector: "Financials",
    },
    {
      Symbol: "MLM",
      Name: "Martin Marietta Materials",
      Sector: "Materials",
    },
    {
      Symbol: "MAS",
      Name: "Masco",
      Sector: "Industrials",
    },
    {
      Symbol: "MA",
      Name: "Mastercard",
      Sector: "Information Technology",
    },
    {
      Symbol: "MTCH",
      Name: "Match Group",
      Sector: "Communication Services",
    },
    {
      Symbol: "MKC",
      Name: "McCormick & Company",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "MCD",
      Name: "McDonald's",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "MCK",
      Name: "McKesson Corporation",
      Sector: "Health Care",
    },
    {
      Symbol: "MDT",
      Name: "Medtronic",
      Sector: "Health Care",
    },
    {
      Symbol: "MRK",
      Name: "Merck & Co.",
      Sector: "Health Care",
    },
    {
      Symbol: "MET",
      Name: "MetLife",
      Sector: "Financials",
    },
    {
      Symbol: "MTD",
      Name: "Mettler Toledo",
      Sector: "Health Care",
    },
    {
      Symbol: "MGM",
      Name: "MGM Resorts International",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "MCHP",
      Name: "Microchip Technology",
      Sector: "Information Technology",
    },
    {
      Symbol: "MU",
      Name: "Micron Technology",
      Sector: "Information Technology",
    },
    {
      Symbol: "MSFT",
      Name: "Microsoft",
      Sector: "Information Technology",
    },
    {
      Symbol: "MAA",
      Name: "Mid-America Apartments",
      Sector: "Real Estate",
    },
    {
      Symbol: "MRNA",
      Name: "Moderna",
      Sector: "Health Care",
    },
    {
      Symbol: "MHK",
      Name: "Mohawk Industries",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TAP",
      Name: "Molson Coors Beverage Company",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "MDLZ",
      Name: "Mondelez International",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "MPWR",
      Name: "Monolithic Power Systems",
      Sector: "Information Technology",
    },
    {
      Symbol: "MNST",
      Name: "Monster Beverage",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "MCO",
      Name: "Moody's Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "MS",
      Name: "Morgan Stanley",
      Sector: "Financials",
    },
    {
      Symbol: "MSI",
      Name: "Motorola Solutions",
      Sector: "Information Technology",
    },
    {
      Symbol: "MSCI",
      Name: "MSCI",
      Sector: "Financials",
    },
    {
      Symbol: "NDAQ",
      Name: "Nasdaq",
      Sector: "Financials",
    },
    {
      Symbol: "NTAP",
      Name: "NetApp",
      Sector: "Information Technology",
    },
    {
      Symbol: "NFLX",
      Name: "Netflix",
      Sector: "Communication Services",
    },
    {
      Symbol: "NWL",
      Name: "Newell Brands",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "NEM",
      Name: "Newmont",
      Sector: "Materials",
    },
    {
      Symbol: "NWSA",
      Name: "News Corp (Class A)",
      Sector: "Communication Services",
    },
    {
      Symbol: "NWS",
      Name: "News Corp (Class B)",
      Sector: "Communication Services",
    },
    {
      Symbol: "NEE",
      Name: "NextEra Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "NLSN",
      Name: "Nielsen Holdings",
      Sector: "Industrials",
    },
    {
      Symbol: "NKE",
      Name: "Nike",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "NI",
      Name: "NiSource",
      Sector: "Utilities",
    },
    {
      Symbol: "NSC",
      Name: "Norfolk Southern",
      Sector: "Industrials",
    },
    {
      Symbol: "NTRS",
      Name: "Northern Trust",
      Sector: "Financials",
    },
    {
      Symbol: "NOC",
      Name: "Northrop Grumman",
      Sector: "Industrials",
    },
    {
      Symbol: "NLOK",
      Name: "NortonLifeLock",
      Sector: "Information Technology",
    },
    {
      Symbol: "NCLH",
      Name: "Norwegian Cruise Line Holdings",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "NRG",
      Name: "NRG Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "NUE",
      Name: "Nucor",
      Sector: "Materials",
    },
    {
      Symbol: "NVDA",
      Name: "Nvidia",
      Sector: "Information Technology",
    },
    {
      Symbol: "NVR",
      Name: "NVR",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "NXPI",
      Name: "NXP",
      Sector: "Information Technology",
    },
    {
      Symbol: "ORLY",
      Name: "O'Reilly Automotive",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "OXY",
      Name: "Occidental Petroleum",
      Sector: "Energy",
    },
    {
      Symbol: "ODFL",
      Name: "Old Dominion Freight Line",
      Sector: "Industrials",
    },
    {
      Symbol: "OMC",
      Name: "Omnicom Group",
      Sector: "Communication Services",
    },
    {
      Symbol: "OKE",
      Name: "Oneok",
      Sector: "Energy",
    },
    {
      Symbol: "ORCL",
      Name: "Oracle",
      Sector: "Information Technology",
    },
    {
      Symbol: "OGN",
      Name: "Organon & Co.",
      Sector: "Health Care",
    },
    {
      Symbol: "OTIS",
      Name: "Otis Worldwide",
      Sector: "Industrials",
    },
    {
      Symbol: "PCAR",
      Name: "Paccar",
      Sector: "Industrials",
    },
    {
      Symbol: "PKG",
      Name: "Packaging Corporation of America",
      Sector: "Materials",
    },
    {
      Symbol: "PH",
      Name: "Parker-Hannifin",
      Sector: "Industrials",
    },
    {
      Symbol: "PAYX",
      Name: "Paychex",
      Sector: "Information Technology",
    },
    {
      Symbol: "PAYC",
      Name: "Paycom",
      Sector: "Information Technology",
    },
    {
      Symbol: "PYPL",
      Name: "PayPal",
      Sector: "Information Technology",
    },
    {
      Symbol: "PENN",
      Name: "Penn National Gaming",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "PNR",
      Name: "Pentair",
      Sector: "Industrials",
    },
    {
      Symbol: "PBCT",
      Name: "People's United Financial",
      Sector: "Financials",
    },
    {
      Symbol: "PEP",
      Name: "PepsiCo",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "PKI",
      Name: "PerkinElmer",
      Sector: "Health Care",
    },
    {
      Symbol: "PFE",
      Name: "Pfizer",
      Sector: "Health Care",
    },
    {
      Symbol: "PM",
      Name: "Philip Morris International",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "PSX",
      Name: "Phillips 66",
      Sector: "Energy",
    },
    {
      Symbol: "PNW",
      Name: "Pinnacle West Capital",
      Sector: "Utilities",
    },
    {
      Symbol: "PXD",
      Name: "Pioneer Natural Resources",
      Sector: "Energy",
    },
    {
      Symbol: "PNC",
      Name: "PNC Financial Services",
      Sector: "Financials",
    },
    {
      Symbol: "POOL",
      Name: "Pool Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "PPG",
      Name: "PPG Industries",
      Sector: "Materials",
    },
    {
      Symbol: "PPL",
      Name: "PPL",
      Sector: "Utilities",
    },
    {
      Symbol: "PFG",
      Name: "Principal Financial Group",
      Sector: "Financials",
    },
    {
      Symbol: "PG",
      Name: "Procter & Gamble",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "PGR",
      Name: "Progressive Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "PLD",
      Name: "Prologis",
      Sector: "Real Estate",
    },
    {
      Symbol: "PRU",
      Name: "Prudential Financial",
      Sector: "Financials",
    },
    {
      Symbol: "PTC",
      Name: "PTC",
      Sector: "Information Technology",
    },
    {
      Symbol: "PEG",
      Name: "Public Service Enterprise Group",
      Sector: "Utilities",
    },
    {
      Symbol: "PSA",
      Name: "Public Storage",
      Sector: "Real Estate",
    },
    {
      Symbol: "PHM",
      Name: "PulteGroup",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "PVH",
      Name: "PVH",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "QRVO",
      Name: "Qorvo",
      Sector: "Information Technology",
    },
    {
      Symbol: "QCOM",
      Name: "Qualcomm",
      Sector: "Information Technology",
    },
    {
      Symbol: "PWR",
      Name: "Quanta Services",
      Sector: "Industrials",
    },
    {
      Symbol: "DGX",
      Name: "Quest Diagnostics",
      Sector: "Health Care",
    },
    {
      Symbol: "RL",
      Name: "Ralph Lauren Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "RJF",
      Name: "Raymond James Financial",
      Sector: "Financials",
    },
    {
      Symbol: "RTX",
      Name: "Raytheon Technologies",
      Sector: "Industrials",
    },
    {
      Symbol: "O",
      Name: "Realty Income Corporation",
      Sector: "Real Estate",
    },
    {
      Symbol: "REG",
      Name: "Regency Centers",
      Sector: "Real Estate",
    },
    {
      Symbol: "REGN",
      Name: "Regeneron Pharmaceuticals",
      Sector: "Health Care",
    },
    {
      Symbol: "RF",
      Name: "Regions Financial Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "RSG",
      Name: "Republic Services",
      Sector: "Industrials",
    },
    {
      Symbol: "RMD",
      Name: "ResMed",
      Sector: "Health Care",
    },
    {
      Symbol: "RHI",
      Name: "Robert Half International",
      Sector: "Industrials",
    },
    {
      Symbol: "ROK",
      Name: "Rockwell Automation",
      Sector: "Industrials",
    },
    {
      Symbol: "ROL",
      Name: "Rollins",
      Sector: "Industrials",
    },
    {
      Symbol: "ROP",
      Name: "Roper Technologies",
      Sector: "Industrials",
    },
    {
      Symbol: "ROST",
      Name: "Ross Stores",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "RCL",
      Name: "Royal Caribbean Group",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "SPGI",
      Name: "S&P Global",
      Sector: "Financials",
    },
    {
      Symbol: "CRM",
      Name: "Salesforce",
      Sector: "Information Technology",
    },
    {
      Symbol: "SBAC",
      Name: "SBA Communications",
      Sector: "Real Estate",
    },
    {
      Symbol: "SLB",
      Name: "Schlumberger",
      Sector: "Energy",
    },
    {
      Symbol: "STX",
      Name: "Seagate Technology",
      Sector: "Information Technology",
    },
    {
      Symbol: "SEE",
      Name: "Sealed Air",
      Sector: "Materials",
    },
    {
      Symbol: "SRE",
      Name: "Sempra Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "NOW",
      Name: "ServiceNow",
      Sector: "Information Technology",
    },
    {
      Symbol: "SHW",
      Name: "Sherwin-Williams",
      Sector: "Materials",
    },
    {
      Symbol: "SPG",
      Name: "Simon Property Group",
      Sector: "Real Estate",
    },
    {
      Symbol: "SWKS",
      Name: "Skyworks Solutions",
      Sector: "Information Technology",
    },
    {
      Symbol: "SNA",
      Name: "Snap-on",
      Sector: "Industrials",
    },
    {
      Symbol: "SO",
      Name: "Southern Company",
      Sector: "Utilities",
    },
    {
      Symbol: "LUV",
      Name: "Southwest Airlines",
      Sector: "Industrials",
    },
    {
      Symbol: "SWK",
      Name: "Stanley Black & Decker",
      Sector: "Industrials",
    },
    {
      Symbol: "SBUX",
      Name: "Starbucks",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "STT",
      Name: "State Street Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "STE",
      Name: "Steris",
      Sector: "Health Care",
    },
    {
      Symbol: "SYK",
      Name: "Stryker Corporation",
      Sector: "Health Care",
    },
    {
      Symbol: "SIVB",
      Name: "SVB Financial",
      Sector: "Financials",
    },
    {
      Symbol: "SYF",
      Name: "Synchrony Financial",
      Sector: "Financials",
    },
    {
      Symbol: "SNPS",
      Name: "Synopsys",
      Sector: "Information Technology",
    },
    {
      Symbol: "SYY",
      Name: "Sysco",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "TMUS",
      Name: "T-Mobile US",
      Sector: "Communication Services",
    },
    {
      Symbol: "TROW",
      Name: "T. Rowe Price",
      Sector: "Financials",
    },
    {
      Symbol: "TTWO",
      Name: "Take-Two Interactive",
      Sector: "Communication Services",
    },
    {
      Symbol: "TPR",
      Name: "Tapestry",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TGT",
      Name: "Target Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TEL",
      Name: "TE Connectivity",
      Sector: "Information Technology",
    },
    {
      Symbol: "TDY",
      Name: "Teledyne Technologies",
      Sector: "Industrials",
    },
    {
      Symbol: "TFX",
      Name: "Teleflex",
      Sector: "Health Care",
    },
    {
      Symbol: "TER",
      Name: "Teradyne",
      Sector: "Information Technology",
    },
    {
      Symbol: "TSLA",
      Name: "Tesla",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TXN",
      Name: "Texas Instruments",
      Sector: "Information Technology",
    },
    {
      Symbol: "TXT",
      Name: "Textron",
      Sector: "Industrials",
    },
    {
      Symbol: "COO",
      Name: "The Cooper Companies",
      Sector: "Health Care",
    },
    {
      Symbol: "HIG",
      Name: "The Hartford",
      Sector: "Financials",
    },
    {
      Symbol: "HSY",
      Name: "The Hershey Company",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "MOS",
      Name: "The Mosaic Company",
      Sector: "Materials",
    },
    {
      Symbol: "TRV",
      Name: "The Travelers Companies",
      Sector: "Financials",
    },
    {
      Symbol: "DIS",
      Name: "The Walt Disney Company",
      Sector: "Communication Services",
    },
    {
      Symbol: "TMO",
      Name: "Thermo Fisher Scientific",
      Sector: "Health Care",
    },
    {
      Symbol: "TJX",
      Name: "TJX Companies",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TSCO",
      Name: "Tractor Supply Company",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "TT",
      Name: "Trane Technologies",
      Sector: "Industrials",
    },
    {
      Symbol: "TDG",
      Name: "TransDigm Group",
      Sector: "Industrials",
    },
    {
      Symbol: "TRMB",
      Name: "Trimble",
      Sector: "Information Technology",
    },
    {
      Symbol: "TFC",
      Name: "Truist Financial",
      Sector: "Financials",
    },
    {
      Symbol: "TWTR",
      Name: "Twitter",
      Sector: "Communication Services",
    },
    {
      Symbol: "TYL",
      Name: "Tyler Technologies",
      Sector: "Information Technology",
    },
    {
      Symbol: "TSN",
      Name: "Tyson Foods",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "USB",
      Name: "U.S. Bancorp",
      Sector: "Financials",
    },
    {
      Symbol: "UDR",
      Name: "UDR",
      Sector: "Real Estate",
    },
    {
      Symbol: "ULTA",
      Name: "Ulta Beauty",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "UAA",
      Name: "Under Armour (Class A)",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "UA",
      Name: "Under Armour (Class C)",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "UNP",
      Name: "Union Pacific",
      Sector: "Industrials",
    },
    {
      Symbol: "UAL",
      Name: "United Airlines",
      Sector: "Industrials",
    },
    {
      Symbol: "UPS",
      Name: "United Parcel Service",
      Sector: "Industrials",
    },
    {
      Symbol: "URI",
      Name: "United Rentals",
      Sector: "Industrials",
    },
    {
      Symbol: "UNH",
      Name: "UnitedHealth Group",
      Sector: "Health Care",
    },
    {
      Symbol: "UHS",
      Name: "Universal Health Services",
      Sector: "Health Care",
    },
    {
      Symbol: "VLO",
      Name: "Valero Energy",
      Sector: "Energy",
    },
    {
      Symbol: "VTR",
      Name: "Ventas",
      Sector: "Real Estate",
    },
    {
      Symbol: "VRSN",
      Name: "Verisign",
      Sector: "Information Technology",
    },
    {
      Symbol: "VRSK",
      Name: "Verisk Analytics",
      Sector: "Industrials",
    },
    {
      Symbol: "VZ",
      Name: "Verizon Communications",
      Sector: "Communication Services",
    },
    {
      Symbol: "VRTX",
      Name: "Vertex Pharmaceuticals",
      Sector: "Health Care",
    },
    {
      Symbol: "VFC",
      Name: "VF Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "VIAC",
      Name: "ViacomCBS",
      Sector: "Communication Services",
    },
    {
      Symbol: "VTRS",
      Name: "Viatris",
      Sector: "Health Care",
    },
    {
      Symbol: "V",
      Name: "Visa",
      Sector: "Information Technology",
    },
    {
      Symbol: "VNO",
      Name: "Vornado Realty Trust",
      Sector: "Real Estate",
    },
    {
      Symbol: "VMC",
      Name: "Vulcan Materials",
      Sector: "Materials",
    },
    {
      Symbol: "WRB",
      Name: "W. R. Berkley Corporation",
      Sector: "Financials",
    },
    {
      Symbol: "GWW",
      Name: "W. W. Grainger",
      Sector: "Industrials",
    },
    {
      Symbol: "WAB",
      Name: "Wabtec",
      Sector: "Industrials",
    },
    {
      Symbol: "WBA",
      Name: "Walgreens Boots Alliance",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "WMT",
      Name: "Walmart",
      Sector: "Consumer Staples",
    },
    {
      Symbol: "WM",
      Name: "Waste Management",
      Sector: "Industrials",
    },
    {
      Symbol: "WAT",
      Name: "Waters Corporation",
      Sector: "Health Care",
    },
    {
      Symbol: "WEC",
      Name: "WEC Energy Group",
      Sector: "Utilities",
    },
    {
      Symbol: "WFC",
      Name: "Wells Fargo",
      Sector: "Financials",
    },
    {
      Symbol: "WELL",
      Name: "Welltower",
      Sector: "Real Estate",
    },
    {
      Symbol: "WST",
      Name: "West Pharmaceutical Services",
      Sector: "Health Care",
    },
    {
      Symbol: "WDC",
      Name: "Western Digital",
      Sector: "Information Technology",
    },
    {
      Symbol: "WU",
      Name: "Western Union",
      Sector: "Information Technology",
    },
    {
      Symbol: "WRK",
      Name: "WestRock",
      Sector: "Materials",
    },
    {
      Symbol: "WY",
      Name: "Weyerhaeuser",
      Sector: "Real Estate",
    },
    {
      Symbol: "WHR",
      Name: "Whirlpool Corporation",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "WMB",
      Name: "Williams Companies",
      Sector: "Energy",
    },
    {
      Symbol: "WLTW",
      Name: "Willis Towers Watson",
      Sector: "Financials",
    },
    {
      Symbol: "WYNN",
      Name: "Wynn Resorts",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "XEL",
      Name: "Xcel Energy",
      Sector: "Utilities",
    },
    {
      Symbol: "XLNX",
      Name: "Xilinx",
      Sector: "Information Technology",
    },
    {
      Symbol: "XYL",
      Name: "Xylem",
      Sector: "Industrials",
    },
    {
      Symbol: "YUM",
      Name: "Yum! Brands",
      Sector: "Consumer Discretionary",
    },
    {
      Symbol: "ZBRA",
      Name: "Zebra Technologies",
      Sector: "Information Technology",
    },
    {
      Symbol: "ZBH",
      Name: "Zimmer Biomet",
      Sector: "Health Care",
    },
    {
      Symbol: "ZION",
      Name: "Zions Bancorp",
      Sector: "Financials",
    },
    {
      Symbol: "ZTS",
      Name: "Zoetis",
      Sector: "Health Care",
    },
  ];
};

export const values = () => {
  return {
    CF: 1.189,
    CTVA: 1.301,
    FMC: 0.752,
    MOS: 2.434,
    MLM: -4.037,
    VMC: -3.488,
    DOW: 1.94,
    CE: 0.85,
    FCX: 2.231,
    NEM: 7.716,
    LYB: 2.96,
    PPG: 8.352,
    SHW: 3.488,
    ECL: 2.386,
    EMN: -0.823,
    IFF: 1.018,
    LIN: 1.681,
    DD: -0.664,
    ALB: -12.363,
    APD: 2.732,
    STLD: -6.554,
    NUE: -4.302,
    OMC: 3.504,
    IPG: 4.841,
    EA: 5.839,
    ATVI: 0.994,
    TTWO: 3.694,
    WBD: 0.887,
    PARA: -2.371,
    NWS: 2.286,
    NWSA: 2.304,
    NFLX: 3.108,
    LYV: 0.277,
    DIS: 3.138,
    FOX: 1.638,
    FOXA: 1.718,
    GOOG: 2.993,
    GOOGL: 3.038,
    META: 2.985,
    MTCH: -8.067,
    T: 4.632,
    VZ: 4.236,
    TMUS: 3.692,
    LUMN: -7.985,
    DISH: -6.264,
    CHTR: 0.975,
    CMCSA: 2.625,
    VFC: -0.046,
    RL: -2.384,
    ROST: 3.894,
    TJX: 1.946,
    CPRT: 0.864,
    KMX: 4.888,
    GM: -1.709,
    F: 3.154,
    TSLA: -4.312,
    LKQ: -2.777,
    APTV: -4.618,
    BWA: -3.614,
    NKE: 0.34,
    MHK: -3.295,
    WHR: 0.544,
    LOW: 3.902,
    HD: 1.874,
    EBAY: 0.504,
    ETSY: -2.229,
    AMZN: 0.848,
    HAS: -0.115,
    HLT: 2.634,
    MAR: 0.265,
    TPR: -3.457,
    WRK: 0.975,
    SEE: 6.192,
    PKG: 2.722,
    IP: 1.141,
    AMCR: 1.8,
    AVY: 2.085,
    BALL: -1.336,
    ROL: 4.188,
    PHM: 2.59,
    NVR: 2.003,
    DHI: 1.702,
    LEN: 1.522,
    LVS: 3.005,
    CZR: 1.417,
    MGM: 0.232,
    WYNN: -0.413,
    YUM: 2.749,
    MCD: 1.651,
    SBUX: 4.254,
    DPZ: 0.244,
    DRI: -1.041,
    CMG: 2.457,
    AZO: 4.136,
    BBWI: -4.215,
    BBY: 1.897,
    AAP: 2.263,
    GPC: -0.234,
    ORLY: 3.157,
    ULTA: 1.48,
    TSCO: 1.775,
    NCLH: -1.824,
    RCL: -3.367,
    EXPE: -3.725,
    BKNG: 1.704,
    CCL: -2.326,
    TAP: 1.059,
    PEP: 1.644,
    MNST: 1.246,
    KO: 1.52,
    KDP: 0.312,
    "BF-B": -1.193,
    STZ: -1.001,
    MDLZ: 1.464,
    HSY: 2.704,
    DLTR: 4.755,
    DG: 2.351,
    COST: 1.275,
    TGT: 4.51,
    WMT: 3.772,
    TSN: 2.936,
    BG: -4.907,
    ADM: 0.532,
    SYY: 0.078,
    KR: -1.998,
    KMB: 2.4,
    EL: -2.126,
    CL: 1.195,
    CLX: 1.235,
    CHD: 3.424,
    NWL: -0.496,
    PG: 3.031,
    SJM: -0.178,
    MKC: 5.062,
    CAG: 1.89,
    CPB: 1.721,
    GIS: 2.387,
    LW: 1.56,
    KHC: 0.905,
    K: 2.316,
    HRL: 3.028,
    MO: -0.202,
    PM: 4.244,
    PXD: 4.014,
    MRO: 8.714,
    OXY: 3.994,
    HES: 6.925,
    FANG: 7.674,
    DVN: 7.512,
    EOG: 6.825,
    EQT: 3.657,
    CTRA: 5.392,
    COP: 8.02,
    APA: 5.792,
    BKR: 3.088,
    HAL: 5.455,
    SLB: 4.107,
    XOM: 7.37,
    CVX: 5.607,
    KMI: 2.667,
    WMB: 2.289,
    TRGP: 5.79,
    OKE: 6.418,
    MPC: -1.022,
    PSX: 4.138,
    VLO: -1.358,
    TROW: -0.958,
    PFG: -0.368,
    STT: 0.186,
    NTRS: 0.551,
    IVZ: -2.179,
    BK: -0.399,
    BLK: -0.18,
    BEN: 0.302,
    AMP: -1.044,
    BAC: -3.593,
    C: -0.392,
    JPM: -1.185,
    WFC: -2.844,
    ZION: -7.764,
    TFC: -7.108,
    USB: -3.065,
    MTB: -4.077,
    RF: -1.983,
    PNC: -5.81,
    KEY: -8.761,
    HBAN: -2.646,
    FRC: -5.75,
    FITB: -4.661,
    CFG: -8.063,
    CMA: -10.713,
    GS: 0.253,
    SCHW: -11.483,
    RJF: -3.845,
    MS: -2.806,
    MKTX: -12.166,
    MA: 1.185,
    SYF: -0.524,
    PYPL: -0.768,
    V: 2.181,
    COF: 0.765,
    DFS: -0.287,
    AXP: -1.534,
    CME: 4.352,
    CBOE: 2.208,
    FDS: -1.371,
    ICE: 4.475,
    SPGI: 1.913,
    MCO: 1.102,
    MSCI: -2.28,
    NDAQ: 0.869,
    HIG: -0.474,
    "BRK-B": 1.667,
    AIG: 3.162,
    ACGL: 1.165,
    AFL: 0.264,
    LNC: -3.217,
    GL: -0.906,
    MET: 3.841,
    PRU: 2.032,
    PGR: 1.35,
    TRV: 0.265,
    WRB: 1.065,
    L: -1.195,
    ALL: 4.722,
    CB: 1.413,
    CINF: 0.497,
    RE: 1.109,
    AIZ: 0.482,
    AJG: 3.323,
    BRO: 4.289,
    AON: 2.837,
    MMC: 2.262,
    WTW: 2.457,
    VRTX: 2.45,
    TECH: 2.748,
    MRNA: 3.905,
    REGN: 0.716,
    INCY: 3.711,
    IDXX: -2.241,
    ILMN: 4.004,
    IQV: 2.167,
    LH: 5.495,
    A: 3.168,
    DGX: 3.488,
    DHR: 0.089,
    CRL: -0.931,
    PKI: 3.06,
    MTD: 2.243,
    TMO: 4.451,
    WAT: 0.729,
    MRK: 6.662,
    OGN: 4.233,
    PFE: 3.23,
    ABBV: 1.772,
    AMGN: 5.12,
    BMY: 2.405,
    BIIB: 3.642,
    LLY: 7.851,
    JNJ: 8.023,
    GILD: 2.903,
    CTLT: -7.906,
    VTRS: 2.833,
    ZTS: 3.068,
    GEHC: 2.373,
    ELV: 6.252,
    HUM: 6.275,
    CVS: 4.94,
    CNC: 3.362,
    CI: 4.665,
    UNH: 9.139,
    MOH: 6.95,
    UHS: 3.69,
    HCA: 5.42,
    DVA: 5.696,
    DXCM: -1,
    EW: 2.217,
    BIO: -1.731,
    BSX: 3.382,
    ALGN: 3.53,
    ABT: 5.668,
    ZBH: 1.46,
    MDT: 1.518,
    PODD: 0.956,
    STE: 2.555,
    SYK: 3.225,
    MCK: 4.483,
    ABC: 5.278,
    CAH: 6.461,
    HSIC: 5.304,
    HOLX: 3.649,
    ISRG: 2.883,
    COO: 3.256,
    BDX: 3.598,
    BAX: 4.243,
    RMD: 3.573,
    XRAY: 4.003,
    WST: 2.598,
    TFX: 6.43,
    WBA: 5.769,
    TXT: -3.511,
    RTX: 1.085,
    TDG: -1.315,
    NOC: 2.024,
    BA: 0.976,
    HII: -0.536,
    HWM: 0.718,
    LMT: 3.332,
    LHX: 1.418,
    GD: 0.961,
    LUV: 0.445,
    AAL: -3.206,
    ALK: 3.249,
    DAL: 0.42,
    UAL: -3.313,
    TT: -7.893,
    MAS: -2.83,
    CARR: -7.228,
    JCI: -6.481,
    HON: 0.19,
    MMM: -0.872,
    VRSK: 0.636,
    EFX: 0.342,
    J: -2.861,
    PWR: -3.354,
    PCAR: -5.349,
    CAT: -4.247,
    DE: -6.729,
    GWW: -4.265,
    FAST: -2.756,
    POOL: -4.612,
    UPS: -1.081,
    FDX: 2.808,
    EXPD: 0.038,
    JBHT: -0.468,
    CHRW: -3.37,
    CSX: -1.014,
    UNP: -2.451,
    WAB: -2.798,
    NSC: -2.031,
    URI: -8.55,
    ALLE: -5.892,
    CTAS: -2.883,
    GPN: 0.581,
    GNRC: -11.556,
    GE: 0.202,
    ETN: -5.464,
    EMR: -2.178,
    DOV: -2.769,
    ITW: -4.189,
    IR: -3.192,
    IEX: -3.64,
    CMI: -5.311,
    AME: -4.619,
    AOS: -6.254,
    XYL: -1.192,
    NDSN: -2.447,
    OTIS: -4.153,
    PH: -6.461,
    PNR: -2.967,
    ROK: -3.996,
    RHI: -2.735,
    PAYX: -6.205,
    ADP: -3.06,
    SNA: -4.893,
    SWK: -4.415,
    ODFL: -1.934,
    RSG: 1.707,
    WM: 3.681,
    CBRE: 0.965,
    CSGP: -0.674,
    VICI: 1.325,
    WELL: 0.858,
    VTR: -4.57,
    PEAK: 0.562,
    HST: 2.03,
    EXR: 2.801,
    PLD: 1.994,
    PSA: 5.864,
    ARE: 0.512,
    BXP: -1.167,
    AVB: 2.54,
    CPT: 0.828,
    ESS: 2.511,
    EQR: 3.526,
    INVH: 3.242,
    MAA: 1.656,
    UDR: 2.97,
    O: 1.08,
    REG: 1.773,
    SPG: 3.152,
    KIM: 2.796,
    FRT: 4.039,
    EQIX: 1.341,
    IRM: 1.197,
    DLR: -2.37,
    CCI: 2.1,
    AMT: 3.124,
    SBAC: 1.589,
    WY: 1.754,
    ZBRA: 1.361,
    MSI: 3.371,
    CSCO: 1.27,
    HPE: 2.513,
    JNPR: 2.817,
    HPQ: 3.886,
    ANET: 0.222,
    NTAP: 1.225,
    STX: 1.677,
    WDC: -4.208,
    AAPL: 1.86,
    APH: -2.205,
    GLW: -0.291,
    TEL: -2.253,
    FIS: 4.371,
    FISV: 0.447,
    EPAM: -1.13,
    DXC: 0.322,
    IBM: 1.873,
    IT: -1.633,
    JKHY: -0.909,
    LDOS: 0.077,
    BR: -1.469,
    ACN: 0.497,
    CTSH: 1.932,
    CDW: -0.175,
    KEYS: -0.44,
    FTV: -3.806,
    GRMN: -0.254,
    TRMB: -4.432,
    TDY: -0.039,
    TER: -5.736,
    KLAC: -0.919,
    LRCX: -4.318,
    AMAT: -2.111,
    AMD: -3.674,
    ADI: 0.634,
    AVGO: 0.561,
    INTC: 4.156,
    TXN: -2.121,
    SWKS: -3.434,
    QCOM: -1.639,
    QRVO: -5.18,
    NVDA: -0.382,
    NXPI: -3.341,
    ON: -4.169,
    MU: -10.261,
    MPWR: -3.583,
    MCHP: -1.669,
    PAYC: -0.094,
    NOW: 6.589,
    PTC: 1.147,
    ROP: 0.705,
    TYL: 1.956,
    INTU: 1.352,
    ADSK: -0.808,
    ANSS: 1.009,
    CDAY: -1.366,
    CDNS: 0.757,
    CRM: -0.676,
    AKAM: 0.886,
    ADBE: 0.754,
    GEN: 3.425,
    FLT: 0.019,
    FFIV: 3.698,
    FTNT: 0.525,
    VRSN: 3.443,
    SNPS: 0.885,
    ORCL: 4.712,
    MSFT: 1.365,
    SEDG: -4.467,
    FSLR: -6.38,
    ENPH: -5.04,
    AES: 2.728,
    SRE: 3.159,
    NRG: 3.707,
    NEE: 2.917,
    SO: 3.115,
    PPL: 3.088,
    PNW: 2.779,
    PEG: 2.983,
    PCG: 4.167,
    WEC: 4.24,
    XEL: 6.883,
    AEE: 3.79,
    AEP: 4.928,
    DTE: 3.882,
    DUK: 2.67,
    D: 3.293,
    CMS: 1.553,
    CNP: 3.72,
    EIX: 3.524,
    ED: 3.575,
    ETR: 4.154,
    ES: 3.83,
    EXC: 4.326,
    EVRG: 5.022,
    FE: 5.905,
    LNT: 3.786,
    ATO: 2.968,
    NI: 3.949,
    AWK: 4.211,
    CEG: 0.817,
  };
};
